// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User_Management.DataAccess.User_Context;

#nullable disable

namespace User_Management.DataAccess.Migrations
{
    [DbContext(typeof(UserManagement_DbContext))]
    partial class UserManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User_Management.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MartialStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfResident")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 17,
                            FirstName = "Amos",
                            Gender = "Male",
                            LastName = "Iqout",
                            MartialStatus = "Single",
                            StateOfResident = "Akwa Ibom"
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Smith",
                            MartialStatus = "Married",
                            StateOfResident = "Lagos"
                        },
                        new
                        {
                            Id = 3,
                            Age = 18,
                            FirstName = "Victor",
                            Gender = "Female",
                            LastName = "James",
                            MartialStatus = "Single",
                            StateOfResident = "Cross Rivers"
                        },
                        new
                        {
                            Id = 4,
                            Age = 20,
                            FirstName = "Blessing",
                            Gender = "Female",
                            LastName = "James",
                            MartialStatus = "Single",
                            StateOfResident = "Rivers"
                        },
                        new
                        {
                            Id = 5,
                            Age = 50,
                            FirstName = "Amarachi",
                            Gender = "Female",
                            LastName = "Favour",
                            MartialStatus = "Married",
                            StateOfResident = "Abia"
                        },
                        new
                        {
                            Id = 6,
                            Age = 65,
                            FirstName = "Stephen",
                            Gender = "Male",
                            LastName = "Michael",
                            MartialStatus = "Married",
                            StateOfResident = "Delta"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
